server:
  port: 9999

spring:
  application:
    name: front-service
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/account_db
    driverClassName: org.postgresql.Driver
    username: masik
    password: 121232
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
