server:
  port: 0

spring:
  application:
    name: front-service
  liquibase:
    enabled: true
  datasource:
    url: jdbc:h2:file:./person_db
    driverClassName: org.h2.Driver
    username: masik
    password: 222
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
